name: Counterstrike
version: '${project.version}'
main: dev.idw0309.counterstrike.Counterstrike
authors: [ IdW0309 ]
api-version: 1.13
description: Play counterstrike (csgo) in minecraft

commands:
  counterstrike:
    description: just a command
